#!/usr/bin/env python3
"""Generate MVP backlog CSV files for Linear import."""

import csv
from pathlib import Path

OUT_DIR = Path(__file__).parent

# Priority: P0 -> Urgent, P1 -> High, P2 -> Medium (Linear)
PRIORITY_MAP = {"P0": "Urgent", "P1": "High", "P2": "Medium"}

ISSUES = [
    # E0 — Plattform-Fundament
    {
        "id": "E0-1",
        "epic": "E0 Plattform-Fundament",
        "title": "Mandanten anlegen und Tenant-Isolation",
        "description": "Als Betreiber möchte ich Mandanten (tenants) anlegen, damit Daten isoliert sind.",
        "acceptance": "- tenant_id in allen Tabellen\n- API lehnt Cross-Tenant-Zugriff ab (403)",
        "priority": "P0",
        "points": 5,
        "sprint": 1,
        "labels": "backend,platform,database",
        "type": "Story",
    },
    {
        "id": "E0-2",
        "epic": "E0 Plattform-Fundament",
        "title": "SSO/OIDC Login",
        "description": "Als User möchte ich mich per Sunrise-SSO anmelden.",
        "acceptance": "- OIDC-Flow implementiert\n- Session/JWT mit Refresh\n- Logout funktioniert",
        "priority": "P0",
        "points": 8,
        "sprint": 1,
        "labels": "backend,auth,security",
        "type": "Story",
    },
    {
        "id": "E0-3",
        "epic": "E0 Plattform-Fundament",
        "title": "RBAC pro API-Request",
        "description": "Als System soll jede API-Anfrage eine Rolle kennen.",
        "acceptance": "- Rollen: end_user, tenant_admin, platform_admin\n- Middleware prüft Rolle pro Endpoint",
        "priority": "P0",
        "points": 5,
        "sprint": 1,
        "labels": "backend,auth,security",
        "type": "Story",
    },
    {
        "id": "E0-4",
        "epic": "E0 Plattform-Fundament",
        "title": "OpenAPI 3.1 Spec + CI-Validierung",
        "description": "Als Entwickler möchte ich eine OpenAPI-Spec für parallele Entwicklung.",
        "acceptance": "- OpenAPI 3.1 im Repo\n- CI bricht bei Breaking Changes",
        "priority": "P0",
        "points": 3,
        "sprint": 1,
        "labels": "backend,api,dx",
        "type": "Story",
    },
    {
        "id": "E0-5",
        "epic": "E0 Plattform-Fundament",
        "title": "Health-Checks und strukturiertes Logging",
        "description": "Als Betreiber möchte ich Health-Checks und strukturierte Logs.",
        "acceptance": "- /health/live und /health/ready\n- Correlation-ID pro Request",
        "priority": "P1",
        "points": 3,
        "sprint": 1,
        "labels": "backend,devops,observability",
        "type": "Story",
    },
    {
        "id": "E0-6",
        "epic": "E0 Plattform-Fundament",
        "title": "Audit-Log für Konfigurationsänderungen",
        "description": "Als Auditor möchte ich Konfigurationsänderungen nachvollziehen.",
        "acceptance": "- audit_log: wer, was, wann, tenant, before/after JSON\n- Alle Schreiboperationen im MVP erfasst",
        "priority": "P0",
        "points": 5,
        "sprint": 1,
        "labels": "backend,security,compliance",
        "type": "Story",
    },
    {
        "id": "E0-T1",
        "epic": "E0 Plattform-Fundament",
        "title": "PostgreSQL HA + Redis Setup",
        "description": "Technische Grundlage: PostgreSQL HA und Redis für Sessions/Queue.",
        "acceptance": "- Managed PostgreSQL mit Replikation\n- Redis für Sessions und Job-Queue\n- Migrations mit Flyway/Liquibase",
        "priority": "P0",
        "points": 8,
        "sprint": 1,
        "labels": "devops,database,infrastructure",
        "type": "Task",
    },
    {
        "id": "E0-T2",
        "epic": "E0 Plattform-Fundament",
        "title": "CI/CD Pipeline",
        "description": "Build, Test und Deploy Pipeline für API und Frontend.",
        "acceptance": "- PR-Checks (Lint, Test, OpenAPI)\n- Deploy auf Staging bei Merge main",
        "priority": "P0",
        "points": 5,
        "sprint": 1,
        "labels": "devops,ci",
        "type": "Task",
    },
    # E1 — Identität & Profil
    {
        "id": "E1-1",
        "epic": "E1 Identität & Profil",
        "title": "GET /me — Profil anzeigen",
        "description": "Als Endnutzer möchte ich nach Login mein Profil sehen (Name, Durchwahl, DID, Sprache).",
        "acceptance": "- GET /api/v1/me liefert DB-Daten\n- UI entspricht Prototyp Übersicht",
        "priority": "P0",
        "points": 3,
        "sprint": 2,
        "labels": "backend,frontend,user-portal",
        "type": "Story",
    },
    {
        "id": "E1-2",
        "epic": "E1 Identität & Profil",
        "title": "Portalsprache wählen (DE/FR/IT/EN)",
        "description": "Als Endnutzer möchte ich die Portalsprache wählen.",
        "acceptance": "- Sprache im Profil gespeichert\n- Bestehende i18n-Keys aus Prototyp",
        "priority": "P0",
        "points": 3,
        "sprint": 2,
        "labels": "frontend,user-portal,i18n",
        "type": "Story",
    },
    {
        "id": "E1-3",
        "epic": "E1 Identität & Profil",
        "title": "SIP-/Präsenzstatus anzeigen (read-only)",
        "description": "Als Endnutzer möchte ich meinen SIP-Status sehen (online/offline).",
        "acceptance": "- Status aus PBX-Registrierung\n- Fallback unbekannt wenn nicht verfügbar",
        "priority": "P1",
        "points": 3,
        "sprint": 2,
        "labels": "backend,frontend,integration",
        "type": "Story",
    },
    {
        "id": "E1-4",
        "epic": "E1 Identität & Profil",
        "title": "Onboarding serverseitig",
        "description": "Als Endnutzer möchte ich Onboarding nur beim ersten Besuch sehen.",
        "acceptance": "- onboarding_completed_at in users\n- Nicht nur localStorage",
        "priority": "P2",
        "points": 2,
        "sprint": 6,
        "labels": "frontend,user-portal",
        "type": "Story",
    },
    # E2 — CDR
    {
        "id": "E2-1",
        "epic": "E2 Anrufprotokoll (CDR)",
        "title": "Eigene Anrufliste im Benutzerportal",
        "description": "Als Endnutzer möchte ich meine letzten Anrufe sehen (Ein/Aus/Verpasst).",
        "acceptance": "- Paginierte Liste\n- Filter nach Richtung\n- Felder wie Prototyp up-calls",
        "priority": "P0",
        "points": 5,
        "sprint": 3,
        "labels": "frontend,backend,user-portal,cdr",
        "type": "Story",
    },
    {
        "id": "E2-2",
        "epic": "E2 Anrufprotokoll (CDR)",
        "title": "Letzte 5 Anrufe auf Übersicht",
        "description": "Als Endnutzer möchte ich auf der Übersicht die 5 letzten Anrufe sehen.",
        "acceptance": "- GET /api/v1/me/cdr?limit=5\n- Widget auf up-overview",
        "priority": "P0",
        "points": 2,
        "sprint": 3,
        "labels": "frontend,user-portal,cdr",
        "type": "Story",
    },
    {
        "id": "E2-3",
        "epic": "E2 Anrufprotokoll (CDR)",
        "title": "Tenant-Admin CDR-Suche",
        "description": "Als Tenant-Admin möchte ich CDR des Mandanten durchsuchen.",
        "acceptance": "- Filter Zeitraum und User\n- Read-only, CSV-Export\n- Keine Aufnahmen im MVP",
        "priority": "P1",
        "points": 5,
        "sprint": 3,
        "labels": "frontend,backend,tenant-admin,cdr",
        "type": "Story",
    },
    {
        "id": "E2-4",
        "epic": "E2 Anrufprotokoll (CDR)",
        "title": "CDR-Import aus PBX",
        "description": "Als System möchte ich CDR aus der PBX importieren.",
        "acceptance": "- Batch-Job alle 5 Min oder Event-Stream\n- cdr_records Tabelle mit Partitionierung",
        "priority": "P0",
        "points": 8,
        "sprint": 3,
        "labels": "backend,integration,cdr",
        "type": "Story",
    },
    # E3 — Weiterleitung
    {
        "id": "E3-1",
        "epic": "E3 Rufweiterleitung",
        "title": "Weiterleitungsregeln lesen",
        "description": "Als Endnutzer möchte ich meine Weiterleitungsregeln lesen.",
        "acceptance": "- 4 Regeltypen: always, busy, no_answer, hours\n- Ziel: Nummer, Durchwahl oder Voicemail",
        "priority": "P0",
        "points": 3,
        "sprint": 4,
        "labels": "backend,frontend,user-portal,forwarding",
        "type": "Story",
    },
    {
        "id": "E3-2",
        "epic": "E3 Rufweiterleitung",
        "title": "Weiterleitungsregeln speichern",
        "description": "Als Endnutzer möchte ich Regeln aktivieren/deaktivieren und Ziele ändern.",
        "acceptance": "- Validierung\n- Immer überschreibt andere Regeln\n- Speichern startet async Provision-Job",
        "priority": "P0",
        "points": 5,
        "sprint": 4,
        "labels": "backend,frontend,user-portal,forwarding",
        "type": "Story",
    },
    {
        "id": "E3-3",
        "epic": "E3 Rufweiterleitung",
        "title": "Provisionierungsstatus in UI",
        "description": "Als Endnutzer möchte ich den Provisionierungsstatus sehen.",
        "acceptance": "- UI zeigt pending / applied / failed\n- Kein showToast als Erfolgs-Feedback",
        "priority": "P0",
        "points": 3,
        "sprint": 4,
        "labels": "frontend,user-portal,forwarding",
        "type": "Story",
    },
    {
        "id": "E3-4",
        "epic": "E3 Rufweiterleitung",
        "title": "Keine-Antwort mit Klingelzeit",
        "description": "Als Endnutzer möchte ich Keine-Antwort mit Klingelzeit (5–60 s) setzen.",
        "acceptance": "- ring_timeout_sec validiert 5–60\n- Wie Prototyp up-forwarding",
        "priority": "P0",
        "points": 2,
        "sprint": 4,
        "labels": "frontend,backend,forwarding",
        "type": "Story",
    },
    {
        "id": "E3-5",
        "epic": "E3 Rufweiterleitung",
        "title": "Ausserhalb Bürozeiten mit Zeitplan",
        "description": "Als Endnutzer möchte ich Ausserhalb Bürozeiten mit Zeitplan verknüpfen.",
        "acceptance": "- 2 vordefinierte Pläne im MVP\n- Kein Custom-Schedule-Editor",
        "priority": "P1",
        "points": 3,
        "sprint": 4,
        "labels": "backend,forwarding",
        "type": "Story",
    },
    {
        "id": "E3-6",
        "epic": "E3 Rufweiterleitung",
        "title": "PBX applyForwardRules",
        "description": "Als System soll die PBX Weiterleitungen anwenden.",
        "acceptance": "- Provisioning-Adapter applyForwardRules\n- Retry 3x, Fehler in UI + Audit-Log",
        "priority": "P0",
        "points": 8,
        "sprint": 4,
        "labels": "backend,integration,forwarding",
        "type": "Story",
    },
    # E4 — Voicemail
    {
        "id": "E4-1",
        "epic": "E4 Voicemail",
        "title": "Voicemail-Nachrichten auflisten",
        "description": "Als Endnutzer möchte ich Voicemail-Nachrichten auflisten.",
        "acceptance": "- Absender, Datum, Dauer, gelesen/ungelesen\n- Paginiert",
        "priority": "P0",
        "points": 3,
        "sprint": 5,
        "labels": "frontend,backend,user-portal,voicemail",
        "type": "Story",
    },
    {
        "id": "E4-2",
        "epic": "E4 Voicemail",
        "title": "Voicemail gelesen/löschen",
        "description": "Als Endnutzer möchte ich Nachrichten als gelesen markieren oder löschen.",
        "acceptance": "- PATCH /api/v1/me/voicemails/{id}\n- Soft-delete, PBX-Sync wenn API vorhanden",
        "priority": "P1",
        "points": 3,
        "sprint": 5,
        "labels": "backend,user-portal,voicemail",
        "type": "Story",
    },
    {
        "id": "E4-3",
        "epic": "E4 Voicemail",
        "title": "Voicemail als Weiterleitungsziel",
        "description": "Als Endnutzer möchte ich Voicemail als Weiterleitungsziel wählen.",
        "acceptance": "- target_type voicemail aus extension.voicemail_box_id\n- Dropdown in Forwarding-UI",
        "priority": "P0",
        "points": 2,
        "sprint": 5,
        "labels": "frontend,forwarding,voicemail",
        "type": "Story",
    },
    {
        "id": "E4-4",
        "epic": "E4 Voicemail",
        "title": "Voicemail-Audio abspielen",
        "description": "Als Endnutzer möchte ich Voicemail-Audio abspielen.",
        "acceptance": "- Streaming aus Object Storage\n- Optional Phase 2 wenn PBX-API fehlt",
        "priority": "P2",
        "points": 5,
        "sprint": 6,
        "labels": "frontend,voicemail,storage",
        "type": "Story",
    },
    # E5 — Tenant User
    {
        "id": "E5-1",
        "epic": "E5 Tenant Benutzerverwaltung",
        "title": "Benutzerliste mit Suche und Filter",
        "description": "Als Tenant-Admin möchte ich alle Benutzer des Mandanten listen und filtern.",
        "acceptance": "- Suche Name/E-Mail/Durchwahl\n- Pagination",
        "priority": "P0",
        "points": 5,
        "sprint": 5,
        "labels": "frontend,backend,tenant-admin",
        "type": "Story",
    },
    {
        "id": "E5-2",
        "epic": "E5 Tenant Benutzerverwaltung",
        "title": "Benutzerdetail mit Geräten",
        "description": "Als Tenant-Admin möchte ich Benutzerdetails inkl. Geräte und SIP-Status sehen.",
        "acceptance": "- Read-only Geräteliste wie Prototyp\n- SIP registration_status",
        "priority": "P0",
        "points": 3,
        "sprint": 5,
        "labels": "frontend,tenant-admin",
        "type": "Story",
    },
    {
        "id": "E5-3",
        "epic": "E5 Tenant Benutzerverwaltung",
        "title": "Benutzer anlegen",
        "description": "Als Tenant-Admin möchte ich einen Benutzer anlegen.",
        "acceptance": "- Name, E-Mail, Durchwahl, Rolle\n- Extension in DB + PBX Provision-Job",
        "priority": "P0",
        "points": 8,
        "sprint": 5,
        "labels": "backend,tenant-admin,integration",
        "type": "Story",
    },
    {
        "id": "E5-4",
        "epic": "E5 Tenant Benutzerverwaltung",
        "title": "Benutzer deaktivieren",
        "description": "Als Tenant-Admin möchte ich einen Benutzer deaktivieren.",
        "acceptance": "- Kein Login mehr\n- Extension in PBX gesperrt",
        "priority": "P0",
        "points": 5,
        "sprint": 5,
        "labels": "backend,tenant-admin,integration",
        "type": "Story",
    },
    {
        "id": "E5-5",
        "epic": "E5 Tenant Benutzerverwaltung",
        "title": "Rollen zuweisen",
        "description": "Als Tenant-Admin möchte ich Rollen zuweisen (Administrator, Benutzer, Agent).",
        "acceptance": "- Map auf RBAC\n- Agent-Rolle vorbereitet für Phase 2 Queues",
        "priority": "P1",
        "points": 3,
        "sprint": 5,
        "labels": "backend,tenant-admin,auth",
        "type": "Story",
    },
    # E6 — Routing read-only
    {
        "id": "E6-1",
        "epic": "E6 Routing (read-only)",
        "title": "Routing-Übersicht Tenant-Admin",
        "description": "Als Tenant-Admin möchte ich die Routing-Übersicht pro Durchwahl sehen.",
        "acceptance": "- Import aus PBX\n- Keine Bearbeitung im MVP",
        "priority": "P1",
        "points": 5,
        "sprint": 6,
        "labels": "frontend,backend,tenant-admin,routing",
        "type": "Story",
    },
    {
        "id": "E6-2",
        "epic": "E6 Routing (read-only)",
        "title": "Admin sieht User-Weiterleitungen",
        "description": "Als Tenant-Admin möchte ich sehen welche Weiterleitungen ein User gesetzt hat.",
        "acceptance": "- Link User-Detail → Forward-Rules read-only",
        "priority": "P1",
        "points": 2,
        "sprint": 6,
        "labels": "frontend,tenant-admin,forwarding",
        "type": "Story",
    },
    # E7 — Provisioning
    {
        "id": "E7-1",
        "epic": "E7 PBX Provisioning Adapter",
        "title": "Abstrakter Provisioning-Port",
        "description": "Als System möchte ich einen abstrakten Provisioning-Port.",
        "acceptance": "- Interface: applyForwardRules, createExtension, deactivateExtension",
        "priority": "P0",
        "points": 5,
        "sprint": 1,
        "labels": "backend,integration",
        "type": "Story",
    },
    {
        "id": "E7-2",
        "epic": "E7 PBX Provisioning Adapter",
        "title": "Job-Queue für Provisioning",
        "description": "Als System möchte ich Jobs in einer Queue verarbeiten.",
        "acceptance": "- Redis/RabbitMQ Worker\n- Retry + Dead-Letter Queue",
        "priority": "P0",
        "points": 5,
        "sprint": 4,
        "labels": "backend,infrastructure",
        "type": "Story",
    },
    {
        "id": "E7-3",
        "epic": "E7 PBX Provisioning Adapter",
        "title": "desired_state vs actual_state",
        "description": "Als System möchte ich desired_state vs actual_state speichern.",
        "acceptance": "- Drift in UI anzeigbar\n- provision_jobs Tabelle",
        "priority": "P0",
        "points": 3,
        "sprint": 4,
        "labels": "backend,database",
        "type": "Story",
    },
    {
        "id": "E7-4",
        "epic": "E7 PBX Provisioning Adapter",
        "title": "Mock-Adapter für Dev/CI",
        "description": "Als Entwickler möchte ich einen Mock-Adapter für lokale Entwicklung.",
        "acceptance": "- Ersetzt PBX in Dev/CI\n- Contract-Tests gegen Interface",
        "priority": "P0",
        "points": 5,
        "sprint": 1,
        "labels": "backend,testing,dx",
        "type": "Story",
    },
    # E8 — Frontend
    {
        "id": "E8-1",
        "epic": "E8 Frontend-Migration",
        "title": "Prototyp nach Vite migrieren",
        "description": "Als Entwickler möchte ich den Prototyp in ein Vite-Projekt überführen.",
        "acceptance": "- css/, js/, i18n/ Struktur\n- Role Bar für Dev erhalten",
        "priority": "P0",
        "points": 13,
        "sprint": 2,
        "labels": "frontend,dx",
        "type": "Story",
    },
    {
        "id": "E8-2",
        "epic": "E8 Frontend-Migration",
        "title": "Mobile Benutzerportal",
        "description": "Als Endnutzer möchte ich das Benutzerportal mobil nutzen.",
        "acceptance": "- Bottom-Nav ≤768px wie Prototyp\n- Responsive Layout",
        "priority": "P0",
        "points": 5,
        "sprint": 2,
        "labels": "frontend,user-portal",
        "type": "Story",
    },
    {
        "id": "E8-3",
        "epic": "E8 Frontend-Migration",
        "title": "API-Client statt showToast",
        "description": "Als Entwickler möchte ich API-Calls für MVP-Flows.",
        "acceptance": "- Fehlerbehandlung und Loading-States\n- Kein showToast für Persistenz",
        "priority": "P0",
        "points": 5,
        "sprint": 2,
        "labels": "frontend,api",
        "type": "Story",
    },
    {
        "id": "E8-4",
        "epic": "E8 Frontend-Migration",
        "title": "Hilfe/Tutorials beibehalten",
        "description": "Als Endnutzer möchte ich Hilfe/Tutorials weiter nutzen.",
        "acceptance": "- Statische Tutorials clientseitig\n- i18n für Tutorial-Texte",
        "priority": "P2",
        "points": 3,
        "sprint": 6,
        "labels": "frontend,user-portal",
        "type": "Story",
    },
    # Hardening Sprint 6
    {
        "id": "H-1",
        "epic": "Hardening & Pilot",
        "title": "E2E-Tests Kernflows",
        "description": "End-to-End Tests für Login, Forwarding, User CRUD, CDR.",
        "acceptance": "- Mindestens 1 E2E pro Epic E1–E5\n- Läuft in CI",
        "priority": "P0",
        "points": 8,
        "sprint": 6,
        "labels": "testing,qa",
        "type": "Task",
    },
    {
        "id": "H-2",
        "epic": "Hardening & Pilot",
        "title": "Mandanten-Isolation Security-Tests",
        "description": "Verifizieren dass Cross-Tenant-Zugriff unmöglich ist.",
        "acceptance": "- Automatisierte Tests für 403-Szenarien\n- Pen-Test light",
        "priority": "P0",
        "points": 5,
        "sprint": 6,
        "labels": "security,testing",
        "type": "Task",
    },
    {
        "id": "H-3",
        "epic": "Hardening & Pilot",
        "title": "Pilot-Mandant Go-Live",
        "description": "1 Pilot-Mandant mit 20–50 Usern produktiv schalten.",
        "acceptance": "- Runbook für Support\n- Monitoring-Dashboard\n- Rollback-Plan",
        "priority": "P0",
        "points": 5,
        "sprint": 6,
        "labels": "devops,pilot",
        "type": "Task",
    },
]

PHASE2 = [
    ("P2-1", "Hunt Groups & Queues", "Hunt Groups und Warteschlangen verwalten", "P2", 13, "Phase 2"),
    ("P2-2", "Geräte-Provisioning", "TENANT_DEVICES, Firmware, TR-069", "P2", 13, "Phase 2"),
    ("P2-3", "Adressbuch + LDAP", "Adressbuch mit LDAP/365-Sync", "P2", 8, "Phase 2"),
    ("P2-4", "Shop & Orders", "Nummernshop und Bestellungen", "P2", 13, "Phase 2"),
    ("P2-5", "Super-Admin Billing", "Mandanten und Billing-Übersicht", "P2", 13, "Phase 2"),
    ("P2-6", "Service Management Trunks", "TRUNKS und Traffic-Monitoring", "P2", 8, "Phase 2"),
    ("P2-7", "Voicemail Audio & Recording", "Audio-Wiedergabe und Aufnahme Self-Service", "P2", 8, "Phase 2"),
    ("P2-8", "Persönliche Anruffilter", "up-settings Filterlisten", "P2", 5, "Phase 2"),
]


def full_description(issue: dict) -> str:
    parts = [issue["description"], "", "**Akzeptanzkriterien:**", issue["acceptance"]]
    if issue.get("api"):
        parts.extend(["", "**API:**", issue["api"]])
    parts.extend(["", f"**Referenz:** Prototyp-ID `{issue['id']}`"])
    return "\n".join(parts)


def write_linear_csv(path: Path) -> None:
    """Linear-friendly CSV: Title, Description, Priority, Status, Labels, Estimate, Project."""
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "Title",
                "Description",
                "Priority",
                "Status",
                "Labels",
                "Estimate",
                "Project",
            ]
        )
        for issue in ISSUES:
            writer.writerow(
                [
                    f"[{issue['id']}] {issue['title']}",
                    full_description(issue),
                    PRIORITY_MAP[issue["priority"]],
                    "Backlog",
                    issue["labels"].replace(",", ";"),
                    issue["points"],
                    issue["epic"],
                ]
            )
        for pid, title, desc, prio, pts, project in PHASE2:
            writer.writerow(
                [
                    f"[{pid}] {title}",
                    desc + f"\n\n**Referenz:** `{pid}` — Phase 2, nicht MVP",
                    PRIORITY_MAP.get(prio, "Low"),
                    "Backlog",
                    "phase-2",
                    pts,
                    project,
                ]
            )


def write_full_csv(path: Path) -> None:
    """Full export with all metadata columns."""
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "ID",
                "Type",
                "Epic",
                "Title",
                "Description",
                "Acceptance Criteria",
                "Priority",
                "Story Points",
                "Sprint",
                "Labels",
                "Linear Priority",
                "Status",
                "Project",
            ]
        )
        for issue in ISSUES:
            writer.writerow(
                [
                    issue["id"],
                    issue["type"],
                    issue["epic"],
                    issue["title"],
                    issue["description"],
                    issue["acceptance"],
                    issue["priority"],
                    issue["points"],
                    issue["sprint"],
                    issue["labels"],
                    PRIORITY_MAP[issue["priority"]],
                    "Backlog",
                    issue["epic"],
                ]
            )
        for pid, title, desc, prio, pts, project in PHASE2:
            writer.writerow(
                [pid, "Story", project, title, desc, "", prio, pts, "", "phase-2", "Low", "Backlog", project]
            )


if __name__ == "__main__":
    write_linear_csv(OUT_DIR / "mvp-backlog-linear.csv")
    write_full_csv(OUT_DIR / "mvp-backlog-full.csv")
    total_points = sum(i["points"] for i in ISSUES)
    print(f"Generated {len(ISSUES)} MVP issues ({total_points} SP) + {len(PHASE2)} Phase-2 items")
